apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-node-app
  labels:
    app: my-simple-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-simple-node-app
  template:
    metadata:
      labels:
        app: my-simple-node-app
    spec:
      containers:
      - name: kubernetes-on-aws
        image: philchrist/kubernetes-on-aws
        ports:
        - containerPort: 80